# Generated by Django 4.1.2 on 2022-11-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remembrall", "0002_post_post_id_user_user_id_alter_post_creator_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_id",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
