# Generated by Django 4.1.2 on 2022-11-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remembrall", "0003_alter_post_post_id_alter_user_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="creator_id",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_id",
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(default="NULL"),
        ),
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(default="NULL"),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.TextField(default="NULL"),
        ),
        migrations.AlterField(
            model_name="post",
            name="ref_link",
            field=models.URLField(default="NULL"),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
