# Generated by Django 4.1.2 on 2022-11-13 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("remembrall", "0004_remove_post_creator_id_remove_post_post_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="creator",
            field=models.ForeignKey(
                default="unknown_user",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
